In [ ]:
#Perform the following operations using R/Python on suitable data sets:
#a) read data from different formats (like csv, xls)
#b) Find Shape of Data
#c) Find Missing Values
#d) Find data type of each column
#e) Finding out Zero's
#f) Indexing and selecting data, sort data,
#g) Describe attributes of data, checking data types of each column,
#h) counting unique values of data, format of each column, converting variable
#data type (e.g. from long to short, vice versa)

In [ ]:
#importing pandas
import pandas as pd

In [ ]:
#reading the data using pd.read_csv
df=pd.read_csv('/content/Heart (1).csv')

In [ ]:
#find shape of data
df.shape

(297, 16)

In [ ]:
#Find Missing Values
df.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [31]:
#dropping null values

df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            0
Thal          0
AHD           0
dtype: int64

In [ ]:
#attributes of data, checking data types of each column
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 297 entries, 0 to 301
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  297 non-null    int64
 1   Age         297 non-null    int64
 2   Sex         297 non-null    int64
 3   ChestPain   297 non-null    object
 4   RestBP      297 non-null    int64
 5   Chol        297 non-null    int64
 6   Fbs         297 non-null    int64
 7   RestECG     297 non-null    int64
 8   MaxHR       297 non-null    int64
 9   ExAng       297 non-null    int64
 10  Oldpeak     297 non-null    float64
 11  Slope       297 non-null    int64
 12  Ca          297 non-null    float64
 13  Thal        297 non-null    object
 14  AHD         297 non-null    object
dtypes: float64(2), int64(10), object(3)
memory usage: 37.1+ KB

In [ ]:
#changing datatype of age to float
df['age']=df['Age'].astype('float')

In [ ]:
df.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            0
Thal          0
AHD           0
dtype: int64

In [32]:
# Indexing and selecting data
df.iloc[0:5,2:6]

   Sex     ChestPain  RestBP  Chol
0    1       typical     145   233
1    1  asymptomatic     160   286
2    1  asymptomatic     120   229
3    1    nonanginal     130   250
4    0    nontypical     130   204

In [ ]:
# sort data

df.sort_values('Age',ascending=True)

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
132,133,29,1,nontypical,130,204,0,2,202,0,0.0,1,0.0,normal,No
101,102,34,1,typical,118,182,0,2,174,0,0.0,1,0.0,normal,No
225,226,34,0,nontypical,118,210,0,0,192,0,0.7,1,0.0,normal,No
117,118,35,0,asymptomatic,138,183,0,0,182,0,1.4,1,0.0,normal,No
283,284,35,1,nontypical,122,192,0,0,174,0,0.0,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42,43,71,0,nontypical,160,302,0,0,162,0,0.4,1,2.0,normal,No
273,274,71,0,asymptomatic,112,149,0,0,125,0,1.6,2,0.0,normal,No
233,234,74,0,nontypical,120,269,0,2,121,1,0.2,1,1.0,normal,No
257,258,76,0,nonanginal,140,197,0,1,116,0,1.1,2,0.0,normal,No
161,162,77,1,asymptomatic,125,304,0,2,162,1,0.0,1,3.0,normal,Yes

In [ ]:

df.describe()

,Unnamed: 0,Age,Sex,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca
count,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000
mean,150.673401,54.542088,0.676768,131.693603,247.350168,0.144781,0.996633,149.599327,0.326599,1.055556,1.602694,0.676768
std,87.323283,9.049736,0.468500,17.762806,51.997583,0.352474,0.994914,22.941562,0.469761,1.166123,0.618187,0.938965
min,1.000000,29.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000
25%,75.000000,48.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.000000,0.000000,0.000000,1.000000,0.000000
50%,150.000000,56.000000,1.000000,130.000000,243.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000
75%,226.000000,61.000000,1.000000,140.000000,276.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,1.000000
max,302.000000,77.000000,1.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000

In [ ]:
##Describe attributes of data, checking data types of each column
df['age'].info()

<class 'pandas.core.series.Series'>
Index: 297 entries, 0 to 301
Series name: age
Non-Null Count  Dtype
--------------  -----
297 non-null    float64
dtypes: float64(1)
memory usage: 4.6 KB